version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build
  unit-test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew test

workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
